//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User_Authorization_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class User_Authorizatoin_System_DbEntities : DbContext
    {
        public User_Authorizatoin_System_DbEntities()
            : base("name=User_Authorizatoin_System_DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Permission_Table> Permission_Table { get; set; }
        public virtual DbSet<Pivot_P_R_Table> Pivot_P_R_Table { get; set; }
        public virtual DbSet<Pivot_R_U_Table> Pivot_R_U_Table { get; set; }
        public virtual DbSet<Role_Table> Role_Table { get; set; }
        public virtual DbSet<User_Table> User_Table { get; set; }
    }
}
