//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User_Authorization_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pivot_R_U_Table
    {
        public int pru_id { get; set; }
        public int pru_user_id { get; set; }
        public int pru_role_id { get; set; }
    
        public virtual Role_Table Role_Table { get; set; }
        public virtual User_Table User_Table { get; set; }
    }
}
